### ISSUE TITLE
Only close the session if auto created.

### ISSUE THREAD

**Issue by Hellowlol** [fondberg/easee#1]
Easee.close should only close the connection is the session was not passed manually. (Ill send a PR for this later)

**Comment by fondberg** [comment]
Right. But why  call close then? Maybe the api is not clear

**Comment by Hellowlol** [comment]
.close should be using to clean up regarding the library. A example: the user passes a shared session and closing this could have unforeseen consequences.

**Comment by fondberg** [comment]
Fixed in v0.7.9
